# STEP 1.1 - Configure serial recovery to use CDC_ACM, which by default uses the USB
#CONFIG_BOOT_SERIAL_CDC_ACM=y

CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_DBG=y

# Ensure the build system doesn't try to use the default key
# This helps confirm that your custom key is actually being used
CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=n
