# STEP 1.1 - Configure serial recovery to use CDC_ACM, which by default uses the USB
#CONFIG_BOOT_SERIAL_CDC_ACM=y

CONFIG_LOG=y
CONFIG_MCUBOOT_LOG_LEVEL_DBG=y

# Signature type
CONFIG_BOOT_SIGNATURE_TYPE_ECDSA_P256=y

# Use the default MCUBoot development key (replace for production)
CONFIG_BOOT_SIGNATURE_KEY_FILE="${WEST_TOPDIR}/rh_sensor/rh_sensor_key.pem"

# Ensure the build system doesn't try to use the default key
# This helps confirm that your custom key is actually being used
CONFIG_MCUBOOT_GENERATE_UNSIGNED_IMAGE=n

# Hardware Acceleration for nRF52840 (CC310)
# In pure Zephyr, this is usually selected automatically via SOC_SERIES_NRF52X
# but you can ensure the entropy source is hardware-backed:
CONFIG_ENTROPY_GENERATOR=y
CONFIG_ENTROPY_NRF5_RNG=y
CONFIG_MULTITHREADING=y